# Generated by Django 5.0.1 on 2024-05-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("render", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="periodoteletrabalho",
            options={
                "verbose_name": "Período Teletrabalho",
                "verbose_name_plural": "Chefia | Períodos Teletrabalho",
            },
        ),
        migrations.AlterField(
            model_name="atividadesteletrabalho",
            name="meta_quantitativa",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="comissaointerna",
            name="funcao",
            field=models.CharField(
                choices=[("presidente", "Presidente"), ("membro", "Membro")],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="despachoencaminhaavaliacao",
            name="mes_avaliacao",
            field=models.IntegerField(default=5),
        ),
    ]
