# Generated by Django 5.0.1 on 2024-02-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadesteletrabalho',
            name='cumprimento',
            field=models.CharField(blank=True, choices=[('cumprida', 'Cumprida'), ('parcialmente_cumprida', 'Parcialmente Cumprida'), ('nao_executada', 'Não Cumprida')], max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='atividadesteletrabalho',
            name='justificativa_nao_cumprimento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comissaointerna',
            name='funcao',
            field=models.CharField(choices=[('presidente', 'Presidente'), ('membro', 'Membro')], max_length=128),
        ),
    ]
