# Generated by Django 5.0.1 on 2024-04-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelodocumento',
            name='setor',
        ),
        migrations.AlterField(
            model_name='comissaointerna',
            name='funcao',
            field=models.CharField(choices=[('membro', 'Membro'), ('presidente', 'Presidente')], max_length=128),
        ),
        migrations.AlterField(
            model_name='modelodocumento',
            name='descricao_modelo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
