# Generated by Django 5.0.1 on 2024-04-11 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("render", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="manifestacaointeresse", name="lotacao",),
        migrations.AddField(
            model_name="manifestacaointeresse",
            name="lotacao_chefia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_lotacao_chefia",
                to="render.lotacao",
            ),
        ),
        migrations.AddField(
            model_name="manifestacaointeresse",
            name="lotacao_servidor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_lotacao_servidor",
                to="render.lotacao",
            ),
        ),
        migrations.AlterField(
            model_name="comissaointerna",
            name="funcao",
            field=models.CharField(
                choices=[("presidente", "Presidente"), ("membro", "Membro")],
                max_length=128,
            ),
        ),
    ]
