# Generated by Django 5.0.1 on 2024-03-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelchangelogsmodel',
            options={'verbose_name': 'Log', 'verbose_name_plural': 'Admin | Logs'},
        ),
        migrations.AddField(
            model_name='portariaspublicadasdoe',
            name='diretor_em_exercicio',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='despachoencaminhaavaliacao',
            name='mes_avaliacao',
            field=models.IntegerField(default=3),
        ),
    ]
