# Generated by Django 5.0.1 on 2024-03-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0002_alter_modelchangelogsmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestacaointeresse',
            name='justificativa_chefia',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
