# Generated by Django 5.0.1 on 2024-04-16 17:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0002_remove_manifestacaointeresse_lotacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlterarAvaliacaoChefia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('data_edicao', models.DateTimeField(auto_now=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('docx', models.FileField(blank=True, null=True, upload_to='generated_docx/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='generated_pdf/')),
                ('justificativa', models.TextField()),
                ('adicionado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_add_by', to=settings.AUTH_USER_MODEL)),
                ('avaliacao_chefia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_avaliacao_chefia', to='render.avaliacaochefia')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modelo', to='render.modelodocumento')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_change_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Justificativa Alteração Avaliação',
                'verbose_name_plural': 'Chefia | Justificativas Alterações Avaliações da Chefia',
            },
        ),
    ]
