# Generated by Django 5.0.1 on 2024-04-08 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0002_alter_lotacao_servidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissaointerna',
            name='funcao',
            field=models.CharField(choices=[('presidente', 'Presidente'), ('membro', 'Membro')], max_length=128),
        ),
        migrations.CreateModel(
            name='Chefia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chefia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_chefia', to='render.lotacao')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_setor', to='render.setor')),
            ],
        ),
    ]
