# Generated by Django 5.0.1 on 2024-04-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0003_alteraravaliacaochefia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alteraravaliacaochefia',
            name='data',
        ),
        migrations.RemoveField(
            model_name='alteraravaliacaochefia',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='alteraravaliacaochefia',
            name='data_edicao',
        ),
        migrations.RemoveField(
            model_name='alteraravaliacaochefia',
            name='docx',
        ),
        migrations.RemoveField(
            model_name='alteraravaliacaochefia',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='alteraravaliacaochefia',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='alteraravaliacaochefia',
            name='pdf',
        ),
    ]
