# Generated by Django 5.0.1 on 2024-04-08 17:39

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Usuário')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('rg', models.CharField(max_length=255, verbose_name='RG')),
                ('cargo', models.CharField(max_length=255, verbose_name='Cargo')),
                ('is_staff', models.BooleanField(default=False, help_text='Define se o usuário tem acesso ao admin', verbose_name='Membro da equipe')),
                ('is_active', models.BooleanField(default=False, help_text='Define se o usuário ativou a conta no email', verbose_name='Ativo')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ('nome',),
            },
            managers=[
                ('objects', authentication.models.UserManager()),
            ],
        ),
    ]
